config/routes.rb
Rails.application.routes.draw do
  resources :ilance_projects

  resources :ilance_categories

  resources :ilance_users

  get "/log-in" => "sessions#new"

  post "/log-in" => "sessions#create"

  get "/log-out" => "sessions#destroy", as: :log_out

   root to: 'sessions#create'

end

app/models/ilance_category.rb
class IlanceCategory < ActiveRecord::Base
	has_many :ilance_projects, :foreign_key => :cid
end

app/models/ilance_project.rb
class IlanceProject < ActiveRecord::Base
	belongs_to :ilance_user, :foreign_key => :user_id
	belongs_to :ilance_category, :foreign_key => :cid 
end

app/models/ilance_user.rb
class IlanceUser < ActiveRecord::Base
	has_many :ilance_projects, :foreign_key => :user_id

	attr_accessor :pass_key
	before_save :encrypt_password
	validates_confirmation_of :pass_key
	

	def encrypt_password
		self.salt = BCrypt::Engine.generate_salt
		self.password = BCrypt::Engine.hash_secret(pass_key, salt)
	end

	def self.authenticate(user_name, pass_key)
		p "==================#{user_name}"
		user = IlanceUser.where(username: user_name).first
		if user && user.password == BCrypt::Engine.hash_secret(pass_key, user.salt)
			user
		else
			nil
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
		@current_user ||= IlanceUser.find(session[:user_id]) if session[:user_id]
	end

	def authenticate_user!
		unless current_user.present?
			redirect_to log_in_path
		end
	end
		
end

app/controllers/ilance_categories_controller.rb
class IlanceCategoriesController < ApplicationController
  before_action :set_ilance_category, only: [:show, :edit, :update, :destroy]

  # GET /ilance_categories
  # GET /ilance_categories.json
  def index
    @ilance_categories = IlanceCategory.all
  end

  # GET /ilance_categories/1
  # GET /ilance_categories/1.json
  def show
  end

  # GET /ilance_categories/new
  def new
    @ilance_category = IlanceCategory.new
  end

  # GET /ilance_categories/1/edit
  def edit
  end

  # POST /ilance_categories
  # POST /ilance_categories.json
  def create
    @ilance_category = IlanceCategory.new(ilance_category_params)

    respond_to do |format|
      if @ilance_category.save
        format.html { redirect_to @ilance_category, notice: 'Ilance category was successfully created.' }
        format.json { render :show, status: :created, location: @ilance_category }
      else
        format.html { render :new }
        format.json { render json: @ilance_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ilance_categories/1
  # PATCH/PUT /ilance_categories/1.json
  def update
    respond_to do |format|
      if @ilance_category.update(ilance_category_params)
        format.html { redirect_to @ilance_category, notice: 'Ilance category was successfully updated.' }
        format.json { render :show, status: :ok, location: @ilance_category }
      else
        format.html { render :edit }
        format.json { render json: @ilance_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ilance_categories/1
  # DELETE /ilance_categories/1.json
  def destroy
    @ilance_category.destroy
    respond_to do |format|
      format.html { redirect_to ilance_categories_url, notice: 'Ilance category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ilance_category
      @ilance_category = IlanceCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ilance_category_params
      params.fetch(:ilance_category, {})
    end
end

app/controllers/ilance_projects_controller.rb
class IlanceProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_ilance_project, only: [:show, :edit, :update, :destroy]

  # GET /ilance_projects
  # GET /ilance_projects.json
  def index
    @ilance_projects = IlanceProject.all
  end

  # GET /ilance_projects/1
  # GET /ilance_projects/1.json
  def show
  end

  # GET /ilance_projects/new
  def new
    @ilance_project = IlanceProject.new
  end

  # GET /ilance_projects/1/edit
  def edit
  end

  # POST /ilance_projects
  # POST /ilance_projects.json
  def create
    @ilance_project = IlanceProject.new(ilance_project_params)

    respond_to do |format|
      if @ilance_project.save
        format.html { redirect_to @ilance_project, notice: 'Ilance project was successfully created.' }
        format.json { render :show, status: :created, location: @ilance_project }
      else
        format.html { render :new }
        format.json { render json: @ilance_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ilance_projects/1
  # PATCH/PUT /ilance_projects/1.json
  def update
    respond_to do |format|
      if @ilance_project.update(ilance_project_params)
        format.html { redirect_to @ilance_project, notice: 'Ilance project was successfully updated.' }
        format.json { render :show, status: :ok, location: @ilance_project }
      else
        format.html { render :edit }
        format.json { render json: @ilance_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ilance_projects/1
  # DELETE /ilance_projects/1.json
  def destroy
    @ilance_project.destroy
    respond_to do |format|
      format.html { redirect_to ilance_projects_url, notice: 'Ilance project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ilance_project
      @ilance_project = IlanceProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ilance_project_params
      params.fetch(:ilance_project, {})
    end
end

app/controllers/ilance_users_controller.rb
class IlanceUsersController < ApplicationController

	def new

	end

	def create
		@user = IlanceUser.new(user_params)
		if @user.save
			flash[:notice] = "Welcome to the site!"
			redirect_to log_in_path
		else
			flash[:alert] = "There was a problem creating your account. Please try again."
			redirect_to :back		
		end
	end

	private
	def user_params
		params.require(:ilance_user).permit(:username, :pass_key, :pass_key_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		#try to authenticate the user - if they authenticate successfully, an instance of the User model is returned
		@user = IlanceUser.authenticate(params[:username], params[:pass_key])
		#if an instance is returned and @user is not nil...
		if @user
		#let the user know they've been logged in with a flash message
		flash[:notice] = "You've been logged in."
		#THIS IS THE MOST IMPORTANT PART. Actually log the user in by storing their ID in the session hash with the [:user_id] key!
		session[:user_id] = @user.id
		#then redirect them to the homepage
		redirect_to "/ilance_projects"
		else
		#whoops, either the user wasn't in the database or their password is incorrect, so let them know, then redirect them back to the log in page
		flash[:alert] = "There was a problem logging you in."
		redirect_to log_in_path
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You've been logged out successfully."
		redirect_to log_in_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ilance_categories_helper.rb
module IlanceCategoriesHelper
end

app/helpers/ilance_projects_helper.rb
module IlanceProjectsHelper
end

app/helpers/ilance_users_helper.rb
module IlanceUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/ilance_categories/_form.html.erb
<%= form_for(@ilance_category) do |f| %>
  <% if @ilance_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ilance_category.errors.count, "error") %> prohibited this ilance_category from being saved:</h2>

      <ul>
      <% @ilance_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ilance_categories/edit.html.erb
<h1>Editing ilance_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @ilance_category %> |
<%= link_to 'Back', ilance_categories_path %>

app/views/ilance_categories/index.html.erb
<h1>Listing ilance_categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ilance_categories.each do |ilance_category| %>
      <tr>
        <td><%= link_to 'Show', ilance_category %></td>
        <td><%= link_to 'Edit', edit_ilance_category_path(ilance_category) %></td>
        <td><%= link_to 'Destroy', ilance_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ilance category', new_ilance_category_path %>

app/views/ilance_categories/new.html.erb
<h1>New ilance_category</h1>

<%= render 'form' %>

<%= link_to 'Back', ilance_categories_path %>

app/views/ilance_categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ilance_category_path(@ilance_category) %> |
<%= link_to 'Back', ilance_categories_path %>

app/views/ilance_projects/_form.html.erb
<%= form_for(@ilance_project) do |f| %>
  <% if @ilance_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ilance_project.errors.count, "error") %> prohibited this ilance_project from being saved:</h2>

      <ul>
      <% @ilance_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ilance_projects/edit.html.erb
<h1>Editing ilance_project</h1>

<%= render 'form' %>

<%= link_to 'Show', @ilance_project %> |
<%= link_to 'Back', ilance_projects_path %>

app/views/ilance_projects/index.html.erb
<h1>Listing ilance_projects</h1>

<table class="table table-hover data-table" border="1" data-page-length='2'>
<thead>
    <tr>
        <th style="width:17.5%">Date Added</th>
        <th style="width:17.5%">Project Title</th>
        <th style="width:17.5%">Category</th>
        <th style="width:17.5%">Username</th>
        <th style="width:10%"></th>
        <th style="width:10%"></th>
        <th style="width:10%"></th>

    </tr>
</thead>
<tbody>
  <% @ilance_projects.each do |ilance_project| %>
  <tr>
    <td><%= ilance_project.date_added %></td>
    <td><%= ilance_project.project_title %></td>
    <td><%= ilance_project.ilance_category.try(:name) %></td>
    <td><%= ilance_project.ilance_user.try(:username) %></td>
    <td><%= link_to 'Show', ilance_project %></td>
    <td><%= link_to 'Edit', edit_ilance_project_path(ilance_project) %></td>
    <td><%= link_to 'Destroy', ilance_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</tbody>
</table>
<%= link_to 'New Ilance project', new_ilance_project_path %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.data-table').DataTable();
  });
</script>

app/views/ilance_projects/new.html.erb
<h1>New ilance_project</h1>

<%= render 'form' %>

<%= link_to 'Back', ilance_projects_path %>

app/views/ilance_projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ilance_project_path(@ilance_project) %> |
<%= link_to 'Back', ilance_projects_path %>

app/views/ilance_users/new.html.erb
<h1>Sign Up HERE!!!!</h1>
<%=form_for IlanceUser.new do |f| %>

<%=f.label :username %>

<%=f.text_field :username %>

<%=f.label :password %>

<%=f.password_field :pass_key %>

<%=f.label :password_confirmation %>

<%=f.password_field :pass_key_confirmation %>

<%=f.submit "Sign Up" %>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Company</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
<span><h3><%= link_to "Logout", log_out_path%></h3></span>
<% if !current_user.present?  %>
  <span><h3><%= link_to "Sign Up", new_ilance_user_path %></h3></span>
<% end %>
</p>
<%= yield %>
</body>
</html>